# Author: Dominick Rocco
# rocco@physics.umn.edu
#
include SoftRelTools/arch_spec_root.mk

$(PACKAGE)  := CVNArt
LIB_TYPE    := shared
LIB         := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
JOBFILES    := $(wildcard *.fcl)

override CPPFLAGS := -I$(NUTOOLS_INC) -I$(NOVADAQ_INC)  $(CPPFLAGS) -I$(FANNHOME)/include -I$(CAFFE_INC) -I$(CAFFE_SRC) -I$(GSL_INC)/gsl -I$(HDF5_INC) -I$(PROTOBUF_INC) -I$(GLOG_INC) -I$(LEVELDB_INC) -I$(LMDB_INC) -I$(GFLAGS_INC)

LIBLINK    := -L$(SRT_PRIVATE_CONTEXT)/lib/$(SRT_SUBDIR) -L$(SRT_PUBLIC_CONTEXT)/lib/$(SRT_SUBDIR) -l$(PACKAGE) -l$(PACKAGE)Func

########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_art.mk
include SoftRelTools/arch_spec_novadaq.mk

override LIBLIBS += $(LOADLIBES)  -L$(ART_LIB)  -lart_Framework_Services_Optional_TFileService_service  -L$(SRT_PRIVATE_CONTEXT)/lib/$(SRT_SUBDIR) -L$(SRT_PUBLIC_CONTEXT)/lib/$(SRT_SUBDIR)  -lGeometry_service -lRecoBase -lRecoBase_dict  -l$(PACKAGE)Func -L$(FANN_LIBRARIES_DIR) -lfann -L$(CAFFE_LIB) -l caffe
